### ISSUE TITLE
`--standard` command to remove inputs

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#8]
Make a command called `--standard` with Argparse that removes the need for any input prompts as it uses the standard search with `python` as the language!

`get_url()` is the function you will have to work most in to remove the input prompts when the option is used.

**Comment by TheShonuff** [comment]
I'm interested in looking at this issue

**Comment by TechWiz-3** [comment]
Cool 👍 shall i assign it to you?

**Comment by TheShonuff** [comment]
Yes!

**Comment by TheShonuff** [comment]
This seemed like it would be straightforward but I'm having trouble even just running a vanilla install. currently after going through the prompts I'm met with this.

`Traceback (most recent call last):
  File "/home/shonuff/Documents/open-source-projects/scout/scout/main.py", line 126, in <module>
    cli()
  File "/home/shonuff/Documents/open-source-projects/scout/scout/main.py", line 120, in cli
    response = request(url)
  File "/home/shonuff/Documents/open-source-projects/scout/scout/main.py", line 66, in request
    response = requests.get(f"{url}&page={page}", headers=HEADERS)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'set' object has no attribute 'items'`

In order to get to this point I had to limit the HEADERS as I was met with this error

`raceback (most recent call last):
  File "/home/shonuff/Documents/open-source-projects/scout/scout/main.py", line 23, in <module>
    HEADERS = {'Authorization': 'token ' + TOKEN}
TypeError: can only concatenate str (not "NoneType") to str`

If I'm installing the app as a user with pip install. I'm met with this error...

`Traceback (most recent call last):
  File "/home/shonuff/Documents/open-source-projects/.venv/bin/scout", line 5, in <module>
    from scout.main import cli
  File "/home/shonuff/Documents/open-source-projects/.venv/lib/python3.10/site-packages/scout/main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by TheShonuff** [comment]
I've got the basics of the argparse working on replit. The plan was to just wrap the try / else with an additional condition that checks if --standard is True or False

**Comment by TechWiz-3** [comment]
> his seemed like it would be straightforward but I'm having trouble even just running a vanilla install. currently after going through the prompts I'm met with this.
> 
> ``

Um yeah that's coz u didn't put a token as instructed in the installation steps in the README. Without a token you will get ratelimited real quick.

We're working on removing reliance on a token in #2

**Comment by TheShonuff** [comment]
I've added the SCOUT_TOKEN=_token_ to the .env file. I've dealt with env files in other Python projects like discord bots. I know others are not experiencing this issue as I see updates to contributions. 

I git cloned the repo

Cd'd into scout

Created a .env with a generated token from GitHub 

Cd scout

Python3 main.py

Then I get the error

**Comment by TechWiz-3** [comment]
If you create a .env file you need to load it first with `load_dotenv()` did you do that?

**Comment by TechWiz-3** [comment]
Are you on UNIX based system or on Windows?

**Comment by TheShonuff** [comment]
new documentation helped. Didn't consider putting the environment variable in my shell

**Comment by TheShonuff** [comment]
I'm on Ubuntu 22.04. I'll remeber the load_dotenv() next time. I was using decouple previously in Python scripts. I apologize for the confusion. I'm trying to do more python lately and did not recognize the difference with os.getenv and load_dotenv... The PR has now been submitted

**Comment by TechWiz-3** [comment]
Oh ok cool.
